# Site settings
title: Jungsoo (Jason) Lee
description: ''
url: 'http://leebebeto.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jungsoo Lee'
  email: bebeto@kaist.ac.kr
  twitter_username: ''
  facebook_username: Jungsoo Lee
  github_username: leebebeto
  linkedin_username:  Jung Soo Lee

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
